<?php
/**

Copyright 2016 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-504a49
Date:    2016-01-15 10:52:44
Version: v1.0-rc11
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

namespace JF;

class Config {

    public static function getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-504a49",
    "email": {
        "to": "formtest@popadom.com",
        "cc": "",
        "bcc": "",
        "subject": "test",
        "template": ""
    },
    "admin": {
        "users": "admin:bcf58",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "smtp",
    "smtp": {
        "host": "localhost",
        "user": "",
        "password": "",
        "security": "none"
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "Your Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "cid": "c1"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                }
            },
            "cid": "c2"
        },
        {
            "label": "",
            "field_type": "phone",
            "field_options": {
                "size": "small",
                "sender": false,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "",
                    "leftText": ""
                },
                "placeholder": "Phone"
            },
            "cid": "c35"
        },
        {
            "label": "",
            "field_type": "text",
            "field_options": {
                "size": "small",
                "sender": false,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    
                    "required": {
                        "enabled": false
                    }
                },
                "addon": {
                    "leftIcon": "",
                    "leftText": ""
                },
                "placeholder": "Number of Guests",
                "description": ""
            },
            "cid": "c27"
        },
        {
            "label": "Comments",
            "field_type": "paragraph",
            "field_options": {
                "validators": {
                    "required": {
                        "enabled": false
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-edit"
                }
            },
            "cid": "c3"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": [

            ],
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "cid": "c100"
        }
    ]
}
<?php /**JSON_END**/

	    $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

} // end of Config class